### ISSUE TITLE
Test on video

### ISSUE THREAD

**Issue by roxanneluo** [princeton-vl/DeepV2D#11]
Hi,

I'd like to test on a video sequence in TUM. I'm wondering how you test on a video sequence.
If the poses are unknown, how do you compute the poses? What's the batch size do you use to optimize the poses? Which images do you sample to compute the pose for a certain frame.

If the poses are known, do you only update the depth for one iteration?

Xuan

**Comment by zachteed** [comment]
Hi, you probably want to run
```
python demos/demo_slam.py --dataset=tum --n_keyframes=3 --clear_points
```
which will run DeepV2D on a video from the TUM sequence. 

Poses are treated as unknowns and estimated during inference by using a differentiable least-squares solver. When running DeepV2D on a video, keyframes are selected based on time increments or if the camera moves by a specified distance.
