### ISSUE TITLE
NYU gt association and pose

### ISSUE THREAD

**Issue by YamamotoSayaka** [princeton-vl/DeepV2D#18]
Hi, thx for sharing the code. 
However, I have one problem about the dataloader for NYUv2.

https://github.com/princeton-vl/DeepV2D/blob/a3fbef1379383f0429ffb3f2556155d4d20f0c9c/deepv2d/data_stream/nyuv2.py#L183-L184

I have already downloaded the NYUv2 raw dataset, and want to generate the tfrecords on my own.
However, it seems that the association file and gt pose file is not provided in the official dataset.
Did you generate it from another approach?

**Comment by zachteed** [comment]
Hi, we used ORB-SLAM v2 in RGB-D mode to estimate camera pose, these are the poses included in the tfrecords file.

**Comment by YamamotoSayaka** [comment]
Many thx!
