### ISSUE TITLE
connecting error when downloading the pretrained model

### ISSUE THREAD

**Issue by theodore-zxd** [princeton-vl/DeepV2D#19]
The pretrained model on "https://www.dropbox.com/s/1cerfm260gqu9bt/models.zip" in the script "./data/download_models.sh" is not reachable. Is there another way to get the pretrained model, such as the google drive? Tks.

![image](https://user-images.githubusercontent.com/22735496/88796791-d5e44400-d1d4-11ea-8957-bb557ca0729f.png)

**Comment by zachteed** [comment]
Hi, you can download the models from this google drive link: https://drive.google.com/file/d/1pEUwOw_aOCIz53dGXOnU3KXArzR41YAV/view?usp=sharing

**Comment by theodore-zxd** [comment]
> Hi, you can download the models from this google drive link: https://drive.google.com/file/d/1pEUwOw_aOCIz53dGXOnU3KXArzR41YAV/view?usp=sharing

Thanks!
