### ISSUE TITLE
code ambiguity

### ISSUE THREAD

**Issue by mhiraoka** [princeton-vl/DeepV2D#23]
Hi, thank you for your great work!

https://github.com/princeton-vl/DeepV2D/blob/master/deepv2d/modules/motion.py#L318

It looks this line needs ```intrinsics_pred = ``` or ```intrinsics = ``` .
Do I misunderstand something?

**Comment by zachteed** [comment]
Hi, you are correct. If you were to train a model which also estimates camera focal lengths you should rewrite
`intrinsics_pred  = intrinsics_vec_to_matrix(self.intrinsics_history[i])`
and also use `is_calibrated=False` in the config file

However, for the experiments in our paper we assume a calibrated camera - which was why the code was not using the predicted intrinsics when computing the loss.

**Comment by mhiraoka** [comment]
I understand the point!
Thank you!
