### ISSUE TITLE
How to load 2-stage checkpoints for evaluation?

### ISSUE THREAD

**Issue by ryancll** [princeton-vl/DeepV2D#29]
Hi @zachteed @heilaw @anewell @jiadeng ,

Thank you for your work! I have a question about the ckpt for demo and evaluation. 

When we train the model we can get two checkpoints for stage_1 and stage_2, but I notice we only need to load one ckpt file for evaluation and demo. How can we get this final ckpt file and could you please explain more about the relationship between this final ckpt and two-stage ckpts got from training.

Thank you so much!

**Comment by zachteed** [comment]
Hi, you should use the stage_2 checkpoint
