### ISSUE TITLE
Questions about intrinsics for ScanNet

### ISSUE THREAD

**Issue by tonyke1993** [princeton-vl/DeepV2D#30]
Hello. Thanks for the great work.

I am trying to run your evaluation code on ScanNet. I think I am using a newer version of ScanNet where some intrinsics file are placed elsewhere. So I got FileNotFound error here:

https://github.com/princeton-vl/DeepV2D/blob/master/deepv2d/data_stream/scannet.py#L111

Can you let me know what intrinsics (with respect to what image size) should be put here so that I can assign them manually?

Also, I am confused why only the depth intrinsics were used:
https://github.com/princeton-vl/DeepV2D/blob/master/deepv2d/data_stream/scannet.py#L143
while I guess the network will need color intrinsics instead.

**Comment by zachteed** [comment]
Hi,

For all the sequences I checked, the depth intrinsics are 
577.8 0, 319.5
0, 577.8 , 239.5
0, 0, 1

I believe they are the same for every frames. The depth and color intrinsics turn out to be the same when the color and depth images are both resized to 480x640.

Also, I just made a small update to scannet.py, so you should use the updated version. The previous code assumed only 1 in every 4 images was downloaded.

**Comment by tonyke1993** [comment]
That works! Thank you.
