### ISSUE TITLE
ScanNet training

### ISSUE THREAD

**Issue by ChenHoy** [princeton-vl/DeepV2D#32]
Hi,
in the paper you train on KITTI, NYU and ScanNet for your best results (Scannet gets the most iterations during stage 1). However, there are only training scipts for  KITTI and NYU present here. 

What is the reason for this? Could this be additionally provided? 

Another question: Afterwards, you report that stage 2 is trained for another 120k iterations. On what benchmark is this? Is this on the individual benchmark, where you report your results or do you train on several as in stage 1?

Best regards!

**Comment by ChenHoy** [comment]
That would be great, thank you! I could not find the split from Tang et al, so this is really really convenient. 

I understand the multi-stage training, but does this mean that you separate training by data set, i.e. you train on NYU (both stage 1 and stage 2 accordingly) and afterwards you train on KITTI, etc.?
I thought, that you would only train stage 1 on all 3 data sets and then afterwards you do train both stages together, because you separated those numbers in your paper. 

Guess:
- You trained as you specified in your yaml files:  [20k, 120k] on NYU, [16k, 120k] on KITTI, ... 
- When restoring a checkpoint your scripts only loads stage 2 training.  Both restored modules would be trained according to the stage 2 training graph. 
- Does this mean that you first train both stages on one benchmark and then load this checkpoint on the next one? But, then there will be no stage 1 training graph executed on the second data set and both modules will be trained according to the stage 2 iterations.  

Is this guess correct or do you restore a checkpoint from one benchmark, then again only train stage 1 and afterwards train stage 2? I would happy if you clarified this. 

Thanks for you quick reply!

Best,
Christian

**Comment by ChenHoy** [comment]
Hello, 
any update on this?

**Comment by zachteed** [comment]
Hi, sorry for the delay, I've just added the ScanNet training code.

The training runs are independent, we are not restoring checkpoints from one dataset for another. The KITTI model is trained independent of NYU. Likewise, the ScanNet model is trained only on ScanNet data.

You can speed up training on ScanNet by initializing with NYU weights (using the --restore_ckpt flag) skipping stage1 training, but this is not necessary

**Comment by ChenHoy** [comment]
No problem! 

Thank you for providing that Code.

Nice to have that confirmed, thank you.
