### ISSUE TITLE
How to implement a single-view demo?

### ISSUE THREAD

**Issue by SYL-322** [princeton-vl/DeepV2D#34]
Hi, I'm trying to implement a single-view NYU evaluation. I noticed that you use 8 frames in your code and estimate the depth map of the first keyframe. I tried to reduce the number of frames to 1, the predicted depth maps are all nan values. I also tried to concatenate two same frames to predict, the resulted depth is not well. 

How to implement a single-view demo correctly?

**Comment by zachteed** [comment]
DeepV2D is designed for multiple views, I expect the results to be poor for single image depth
