### ISSUE TITLE
Question about pose preprocessing

### ISSUE THREAD

**Issue by jwh97nn** [princeton-vl/DeepV2D#38]
Hi,

I have a question about retrieving the pose data.
As referenced below, after the pose is converted from quaternion to matrix, it follows by an inverse operation. Why is this inverse operation necessary?

https://github.com/princeton-vl/DeepV2D/blob/eb362f2f25338faf5adbd7818f1517018bfbc4b5/deepv2d/data_stream/nyuv2.py#L112-L113

Thanks

**Comment by zachteed** [comment]
The inverse operator converts poses from "world" coordinates to "camera" coordinates. This is necessary because we use camera coordinates for training.
