### ISSUE TITLE
Why img is flip before resize

### ISSUE THREAD

**Issue by sconlyshootery** [princeton-vl/DeepV2D#43]
https://github.com/princeton-vl/DeepV2D/blob/eb362f2f25338faf5adbd7818f1517018bfbc4b5/deepv2d/slam.py#L273
Thank you for your great work and codes.
I am new to tensorflow, I want to know why here img is flip before resize?

**Comment by zachteed** [comment]
Hi, ::-1 reverses the channel dimension. Some libraries load images in RGB format while others use BGR. This just reversed the channels.

**Comment by sconlyshootery** [comment]
thanks your reply, you have been very helpful.
